name: app_admin_panel
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # =========================================================
  # =====> FIREBASE VERSIONS ZIKOSOYE (COMPATIBLE V3+) <=====
  # =========================================================
  firebase_core: ^3.6.0        # <== Updated for better Web support
  firebase_auth: ^5.3.1        # <== Updated
  cloud_firestore: ^5.4.4      # <== Updated for stability
  firebase_database: ^11.1.0   
  cloud_functions: ^5.1.0      
  
  intl: ^0.19.0
  fl_chart: ^0.68.0
  youtube_player_flutter: ^8.1.2 
  http: ^1.2.2                 # <== Updated (Ingenzi cyane kuri Full Photo Bytes)

  url_launcher: ^6.3.0         
  cached_network_image: ^3.4.1 

  # ZIFAYILI NA CLOUDFLARE R2
  file_picker: ^8.1.2          
  video_player: ^2.9.1
  mime: ^1.0.5
  provider: ^6.1.2

  cupertino_icons: ^1.0.8
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Niba ufite assets (amashusho), ntugahabwe kwibagirwa kuzishyira hano
  # assets:
  #   - assets/images/