// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT-L2IhMZsq264VR1ZDAiPi-S0eSGugc4',
    appId: '1:93565364847:web:5f4eed3ca2017fc2d43b9a',
    messagingSenderId: '93565364847',
    projectId: 'jembe-talk-1',
    authDomain: 'jembe-talk-1.firebaseapp.com',
    databaseURL: 'https://jembe-talk-1-default-rtdb.firebaseio.com',
    storageBucket: 'jembe-talk-1.firebasestorage.app',
    measurementId: 'G-D6N9MMVEZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlYA92-pX-P5Q1b6ZtJHx56uui9qCvtKM',
    appId: '1:93565364847:android:23faf8dab0d9d4efd43b9a',
    messagingSenderId: '93565364847',
    projectId: 'jembe-talk-1',
    databaseURL: 'https://jembe-talk-1-default-rtdb.firebaseio.com',
    storageBucket: 'jembe-talk-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlPlxw20mp-JvwEar1gtA2cFeE86lmFiM',
    appId: '1:93565364847:ios:43406134af445b17d43b9a',
    messagingSenderId: '93565364847',
    projectId: 'jembe-talk-1',
    databaseURL: 'https://jembe-talk-1-default-rtdb.firebaseio.com',
    storageBucket: 'jembe-talk-1.firebasestorage.app',
    androidClientId: '93565364847-a34liq8nveprmpcakqp8co769n59r7qu.apps.googleusercontent.com',
    iosClientId: '93565364847-qjibikpp3kmnde1tgqrpndo9jeat6895.apps.googleusercontent.com',
    iosBundleId: 'com.example.appAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlPlxw20mp-JvwEar1gtA2cFeE86lmFiM',
    appId: '1:93565364847:ios:43406134af445b17d43b9a',
    messagingSenderId: '93565364847',
    projectId: 'jembe-talk-1',
    databaseURL: 'https://jembe-talk-1-default-rtdb.firebaseio.com',
    storageBucket: 'jembe-talk-1.firebasestorage.app',
    androidClientId: '93565364847-a34liq8nveprmpcakqp8co769n59r7qu.apps.googleusercontent.com',
    iosClientId: '93565364847-qjibikpp3kmnde1tgqrpndo9jeat6895.apps.googleusercontent.com',
    iosBundleId: 'com.example.appAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT-L2IhMZsq264VR1ZDAiPi-S0eSGugc4',
    appId: '1:93565364847:web:d516e3b94eb6e8d9d43b9a',
    messagingSenderId: '93565364847',
    projectId: 'jembe-talk-1',
    authDomain: 'jembe-talk-1.firebaseapp.com',
    databaseURL: 'https://jembe-talk-1-default-rtdb.firebaseio.com',
    storageBucket: 'jembe-talk-1.firebasestorage.app',
    measurementId: 'G-FF1S9VMJGG',
  );

}